sphinx-apidoc -f -o "source\popupcad" "C:\Users\daukes\code\popupcad\popupcad"
REM sphinx-apidoc -f -o "source\popupcad_gazebo" "C:\Users\danb0b\code\popupcad\popupcad_gazebo"
sphinx-apidoc -f -o "source\popupcad_manufacturing_plugins" "C:\Users\daukes\code\popupcad\popupcad_manufacturing_plugins"
sphinx-apidoc -f -o "source\api_examples" "C:\Users\daukes\code\popupcad\api_examples"
sphinx-apidoc -f -o "source\dev_tools" "C:\Users\daukes\code\popupcad\dev_tools"